### ISSUE TITLE
Can not decompile luac with luadec and unluac

### ISSUE THREAD

**Issue by ZuzooVn** [viruscamp/luadec#55]
I know that the lua version is stored in the 5th byte of the luac file (the header). Here's the first few bytes of a `luac` file I have:

`6D 6D 64 64 74 32
`

The 5th byte is `74`. Is [My Luac][3] file LuaJIT bytecode?

I am trying to decompile this file and receive this error by using [unluac][1]

    Exception in thread "main" java.lang.IllegalStateException: The input file does not have the signature of a valid Lua file.
	at unluac.parse.BHeader.<init>(BHeader.java:41)
	at unluac.Main.file_to_function(Main.java:71)
	at unluac.Main.main(Main.java:42)

and below is error by using [luadec (lua 5.1)][2] 

    '=' expected near '?'

 How can I decompile this file type?

  [1]: https://sourceforge.net/projects/unluac/
  [2]: https://github.com/viruscamp/luadec
  [3]: https://1drv.ms/u/s!AkIxUn6cSIX6sAPOoYdgsLT4Najf

**Comment by ZuzooVn** [comment]
Sorry for any inconvenience
@viruscamp Do you have any recommendation?

**Comment by ZuzooVn** [comment]
Hey anybody has the recommendation?

**Comment by ziggadyzig25** [comment]
Hi ZuzooVn,
Just curious if you ever found out how to do this.  I'm brand new to Lua/Luajit and I think I am trying to do the same thing.

**Comment by Bam810bam321** [comment]
Remember is mostly Binary if its any other type of encryption it might not work
